config/routes.rb
ProfilePilot::Application.routes.draw do
  devise_for :users

  resources :users do
    resources :projects
  end

  root :to => "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
    attr_accessible :client, :desc, :due_time, :estimate, :project, :start_time
  belongs_to :user


  ESTIMATE = ["1 hour", "2 hours", "1 day", "2 days", "1 week", "1 month"]
  PROJECT  =['Test','Run','Fast']
  CLIENT   =['John','Mat','Philip']
  #SUPPLY_UNITS = ["KVArh", "kWh", "m3"]
  #SUBTYPES = ["Active Power", "Reactive Power", "Gas", "Water", "Wastewater"]



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :projects
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  def new
    @project=current_user.projects.new



    #respond_to do |format|
    #  format.html # new.html.erb
    #  format.json { render json: @company }
    #end
  end

  # GET /companies/1/edit
  def edit
    @project = current_user.projects.find(params[:id])
  end

  def index
    @projects = Project.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end

  end

  # POST /companies
  # POST /companies.json
  def create
    @project = current_user.projects.create(params[:project] )
    respond_to do |format|
      if @project.save
         format.html { redirect_to user_project_path current_user.id,@project.id }
        else
          render 'new', :message => "there is some error"
      end
    end
  end

  def show
    @project = current_user.projects.last

  end

  def destroy
    @project = current_user.projects.find(params[:id])
    @project.delete
    respond_to do |format|
      format.html {redirect_to :root }
      format.json { render json: @project }
    end
  end

  def update
    @project = current_user.projects.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to user_project_path(current_user.id ,@project.id), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def new
  end

  def create
    #@user=User.new(params[:user])
    #if @user.save
    # render 'show'
    #end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index

  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_body.html.erb
<div id="wrapper2">
  <div id="newsletter" class="container">
    <div class="title">
      <h2>Projects List</h2>
      <span class="byline"></span> </div>
    <div class="content">
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!--
<ul class="nav nav-pills">
  <li class="active">
    <a href="#">Dashboard</a>
  </li>
  <li><%= link_to 'People' %></li>
  <li><%= link_to 'Estimates'%></li>
  <li><%= link_to 'Projects' , user_projects_path(current_user.id)%></li>
  <li><%= link_to 'Costings'%></li>
  <li><%= link_to 'Calendar'%></li>
  <li><%= link_to 'Settings' %></li>
</ul>-->
<div id="header-wrapper">
  <div id="header" class="container">
    <div id="menu">
      <ul>
        <li><%= link_to 'People' %></li>
        <li><%= link_to 'Estimates'%></li>
        <li><%= link_to 'Projects' , user_projects_path(current_user.id)%></li>
        <li><%= link_to 'Costings'%></li>
        <li><%= link_to 'Calendar'%></li>
        <li><%= link_to 'Settings' %></li>
        <li><%= link_to 'SignOut' ,destroy_user_session_path ,:method  => :delete%></li>
      </ul>
    </div>
    <div id="logo">
      <h1><a href="#">Construction Pioneer</a></h1>
     </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProfilePilot</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in?  %>
<%= render 'layouts/header' %>
<%end%>
<%= yield %>

</body>
</html>

app/views/projects/_form.html.haml
- if @project.errors.any?
  #error_explanation
    %h2
      = pluralize(@project.errors.count, "error")
      prohibited this company from being saved:
    %ul
      - @company.errors.full_messages.each do |msg|
        %li= msg


= f.label :estimate
= select(:project, :estimate, Project::ESTIMATE , {:include_blank => true})

= f.label :client
= select(:project, :client, Project::CLIENT , {:include_blank => true})

= f.label :desc
= f.text_field :desc

= f.label :project
= select(:project, :project, Project::PROJECT , {:include_blank => true})

= f.label :due_time
= f.date_select(:due_time, order: [:day, :month, :year])


= f.label :start_time
= f.date_select(:start_time,  order: [:day, :month, :year])
%br
= f.submit



-#= form_for(@company) do |f|
-#  - if @company.errors.any?
-#    #error_explanation
-#      %h2
-#        = pluralize(@company.errors.count, "error")
-#        prohibited this company from being saved:
-#      %ul
-#        - @company.errors.full_messages.each do |msg|
-#          %li= msg
-#  .field
-#  = f.label :name
-#  %br/
-#  = f.text_field :name
-#  .field
-#  = f.label :description
-#  %br/
-#  = f.text_area :description
-#  .field
-#  = f.label :logo
-#  %br/
-#  = f.text_area :logo
-#
-#  -#=collection_select(:user, :user_id, User.all,
-#  -#                  :id, :id,
-#  -#                 {:prompt => 'select user for company'})
-#
-#  = select_tag("user[user_id]", options_from_collection_for_select(User.find(:all), "id", "name", params[:user]),)
-#  .actions
-#  = f.submit

app/views/projects/destroy.html.haml
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.haml
= form_for @project, url: {:action=>"update"} do |f|
  = render :partial=> "form", :locals=> {f: f }

app/views/projects/index.html.haml
#wrapper2
  #newsletter.container
    .title
      %h2 Projects List
      %span.byline
    .content
      %table.table.table-striped
        %tr
          %th Estimate
          %th Project
          %th Client
          %th Description
          %th Start-Time
          %th End-Time
          %th
          %th
          %th
        -@projects.each do |project|
          %tr
            %td= project.estimate
            %td= project.project
            %td= project.client
            %td= project.desc
            %td= project.start_time
            %td= project.due_time
            %td= link_to 'Delete', user_project_path(current_user.id,project.id), :method => :delete
            %td= link_to 'Edit', edit_user_project_path(current_user.id,project.id)
            %td= link_to 'Create' ,new_user_project_path(current_user.id)
    %br/

app/views/projects/new.html.haml
= form_for(@project , :url => { :action => "create" }) do |f|
 = render :partial=> "form", :locals=> {f: f }

app/views/projects/show.html.haml
#wrapper2
  #newsletter.container
    .title
      %h2 Projects List
      %span.byline
    .content
      %table.table.table-striped
        %tr
          %th Estimate
          %th Project
          %th Client
          %th Description
          %th Start-Time
          %th End-Time
          %th
          %th
          %th
          %tr
            %td= @project.estimate
            %td= @project.project
            %td= @project.client
            %td= @project.desc
            %td= @project.start_time
            %td= @project.due_time
            %td= link_to 'Delete', user_project_path(current_user.id,@project.id), :method => :delete
            %td= link_to 'Edit', edit_user_project_path(current_user.id,@project.id)
            %td= link_to 'Create' ,new_user_project_path(current_user.id)
      %br/

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<%= link_to 'Sign_Out' ,destroy_user_session_path ,:method => :delete %>

<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>